name: "detect-vfr"
platform: "onnxruntime_onnx"
max_batch_size: 4
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [1, 224, 224]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [13, 224, 224]
  }
]
instance_group [
  {
    kind: KIND_CPU
    count: -1
  }
]
optimization {
    graph { level: 2 }
}

