name: "appearance"
platform: "onnxruntime_onnx"
max_batch_size: 20

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [1, 224, 224, 16]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [24]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: -1
  }
]

optimization {
    graph { level: 2 }
}
